[project]
name = "pygame-ce-extras"
version = "0.0.2"
description = "pygame-ce additions/helpers"
readme = "README.md"
authors = [
    { name = "recreational-projects", email = "205627218+recreational-projects@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pygame-ce>=2.5.2",
]
urls = { "source" = "https://github.com/recreational-projects/pygame-ce-extras" }

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.15.10",
]

[tool.ruff.lint]
future-annotations = true
select = ["ALL"]
ignore = [
    "COM812",  # missing-trailing-comma. Conflicts with ruff format
    "D", # pydocstyle
]
extend-safe-fixes = [
    "TC",  # flake8-type-checking
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
