[project]
name = "pygame-ce-extras"
version = "0.0.5"
description = "pygame-ce additions/helpers"
readme = "README.md"
authors = [
    { name = "recreational-projects", email = "205627218+recreational-projects@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pygame-ce>=2.5.2",
]
urls = { "source" = "https://github.com/recreational-projects/pygame-ce-extras" }

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pdoc>=16.0.0",
    "pytest>=9.0.3",
    "ruff>=0.15.11",
]

[tool.ruff.lint]
future-annotations = true
select = ["ALL"]
ignore = [
    "COM812",  # missing-trailing-comma. Conflicts with ruff format
    "D105", # undocumented-magic-method
]
extend-safe-fixes = [
    "TC",  # flake8-type-checking
]

[tool.ruff.lint.per-file-ignores]
# Not relevant in tests:
"tests/*" = [
    "D",
    "PLR2004", # magic-value-comparison
    "S101", # assert
]
